### PR TITLE
display normalised version of variant graph

### PR DESCRIPTION
**Pull request by seretan**
Improvements:
- actually delete merged nodes
- collect 't' forms and show on collapsed node

### CODE REVIEW

**Comment by tla** [comment]
Hi Violeta - I have a question and a comment about this change. 

First the comment - rather than creating a new COLLATED relationship, in the past I have used a RELATED relationship of type 'collated' to mean the same thing. By default the 'collated' relation has the property `is_weak` set to `true`, which means that it will be removed if a different set of readings should be aligned. Also it means that the user can normalise along e.g. 'spelling' relations that are already set, instead of having to add a new 'collated' one.

Second the question - once you ask for a normalised graph, can you get the non-normalised version back? I have only looked briefly at the code but it looks like, even though the non-normalised nodes aren't deleted, the SEQUENCE relationships are changed...?

**Comment by seretan** [comment]
OK -- I wasn't sure RELATED had the same purpose, so I should fix that and use RELATED rather than COLLATED. 

Re graph: To get the default graph back, we would need an "undo" operation for merge, wouldn't we? Is there one? 

In any case, I should use a parameter for choosing between normalised/default. In DisplayOptionModel, what is "normalise" for? Shall I use it for my purpose?

**Comment by tla** [comment]
For this I would recommend not actually changing the graph in the database - rather, I would assemble a dot file that shows only one node per merged cluster, and that is the node that further relations are attached to. 

Actually, maybe you should have a look at the `RelationTypeModel`, and we should discuss it further - a lot of logic for handling this problem is already in there, including how to propagate relations transitively, and in a kind of hierarchy, based on how the relation types are defined. For example:
* In the defaults from Stemmaweb, the 'collated' relation type is **weak** - that means it can be removed if anything stronger conflicts with it - i.e. if something needs to be re-aligned.
* Relations can also be **transitive**, meaning that e.g. if A and B are spelling variants of each other, and so are B and C, then it follows that A and C are too.
* Relations also have a **bindlevel**, which is a way of establishing a rough hierarchy - so if A and B are spelling variants, and B and C get marked as grammatical variants, it follows that A and C are also grammatical variants.

All this means, among other things, that if the editor is using the normalised graph in Stemmaweb and makes a grammatical link between two normalised forms, then all the right relations will automatically be made with the "hidden" variant forms, *as long as they are still in the database.*

And yes, this is what "normalise" is for in the `DisplayOptionModel` - I put the option in a while ago even though I never got around to implementing it.

**Comment by seretan** [comment]
Thanks, Tara. I see the complexity of the issue...

Just one question for now: When you merge readings, in the default graph version, do you actually change the graph? (I presume the answer is yes.) But is there already a situation when you graphically merge nodes, but the graph behind remains unchanged?

The batch annotation of relations (using groups of nodes rather than nodes) is very appealing.

It makes me think of the hypergraph thing.

**Comment by tla** [comment]
Yes, all of the operations in Reading.java actually change the graph - they are for when the collation needs to be corrected somehow. I've just pushed a lot of changes in the last day or two to be able to "virtually" merge nodes in tabular output (e.g. JSON, CSV) but that logic hasn't yet been used in any other output like dot or GraphML.

I'm still pondering the hypergraph in the back of my mind - sometimes I think that witnesses should never share reading nodes, but rather that identical readings across witnesses should be linked together like a relation (type "identical" maybe?) or with a hypernode. That would be a huge redesign though, that would probably have to wait until at least my project is done...

**Comment by seretan** [comment]
Sounds very interesting. Thank you for your thoughts. Then there would be a virtual, hypergraph level, and from each hypernode we could visit/expand the actual nodes behind...

Both hypernodes and ordinary nodes would live in the graph, but on different levels, and users may choose at which level to work.

Operations may be permitted at both levels, and each level is aware of what happens on the other. (Maybe I stop here for now :))

**Pull request closed without merging**
